### PR TITLE
Support slim require

### PR DESCRIPTION
**Pull request by bitencode**
HI @cognitom,
Here are a set of changes and a test that support using the optional plug-ins the come with slim. Specifically, I added and test the 'slim/include' plug-in that allows including common markup from multiple slim files.

### CODE REVIEW

**Comment by bitencode** [comment]
I see that today while I was working on this, you merge a pull request from @dmke that adds -l, and -t options. I wrote this as a generic require so that users of gulp-slim could require any ryby plug-in/library they needed to.  If you would prefer to go with a more simple interface I can change this to just be a -i option instead.

**Comment by jvmccarthy** [comment]
Hi @cognitom, to support including slim files in the same directory, I also added a `chdir` option.  This option allows for changing the working directory of slim to the file that is currently being processed.  That way, if the file includes other files in the same directly, they are correctly picked up.  (This appears to work automatically when passing a file to the slim engine instead of just the file contents.)

**Comment by Nu-hin** [comment]
I agree, this is a very welcome addition. Please consider merging.

**Comment by phyllisstein** [comment]
:+1: Would be great to see this merged in!

**Comment by cognitom** [comment]
@bitencode @jvmccarthy @Nu-hin @phyllisstein sorry for my long absence on this repo :scream_cat: 
If one of you still have an interest on this PR, I'd like to invite you to the collaborator. How about?
(before merge this, it needs to resolve the conflict, I think)

**Comment by jvmccarthy** [comment]
Thanks @cognitom.  The merge didn't seem that bad, but now I'm running into a failing test (should include additional file with include plugin).  I'll see if I can get this test fixed but have pushed it a new branch, [support_slim_require_failing](https://github.com/bitencode/gulp-slim/tree/support_slim_require_failing), in case someone else wants to look at it.

Thanks for offering to make me a collaborator.  Actually, we've moved on from slim to jade.  In my opinion, jade is simply the templating engine to use with node.js tooling.  I'll try to get this PR in but no longer use gulp-slim.

**Comment by cognitom** [comment]
@jvmccarthy thanks!
Yeah, agreed. In the JavaScript ecosystem, jade is better option. `gulp-slim` is needed only when we interact with Rails. BTW, recently I prefer the approach like react.js instead of the template engines.

**Comment by jvmccarthy** [comment]
@cognitom Ok, I've got the merge resolved.  Thanks for the pointer to react.js.  I've read up a bit on it and should give it a try.  (Currently using angular and jade templates with webpack.  Enjoying webpack so far.)

**Comment by cognitom** [comment]
@jvmccarthy Looks nice! Thank you. I'll merge and publish it as v0.3.0 soon.

BTW, don't miss it, too. Riot.js is my favourite ;)
https://muut.com/riotjs/

**Comment by cognitom** [comment]
Done.
https://www.npmjs.com/package/gulp-slim

Thanks again @bitencode and @jvmccarthy !

**Pull request merged**
